# Arrays

In [23]:
import numpy
def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    a=numpy.array(arr,float)
    return a
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Shape and Reshape

In [42]:
import numpy as np
n=list(map(int,input().split()))
m=np.array(n)
m.shape=(3,3)
print(m)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [1]:
import numpy as np
x,y=map(int,input().split())
a=np.array([input().split() for _ in range(x)],int)
print(a.transpose())
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate

In [2]:
import numpy as np
M,N,P=map(int,input().split())
a=np.array([input().split() for _ in range(M)],int)
b=np.array([input().split() for _ in range(N)],int)
print(np.concatenate((a,b),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeros and Ones


In [12]:
import numpy as p
arr=list(map(int, input().split()))
print(p.zeros(arr, dtype = p.int))
print(p.ones(arr, dtype = p.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [17]:
import numpy as k
i,j = map(int, input().split(' '))
k.set_printoptions(sign=' ')
print(k.eye(i,j))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [68]:
import numpy as np
x,y = map(int,input().split())
p=np.array([input().split() for a in range(x)],int)
q=np.array([input().split() for a in range(x)],int)
print(p+q)
print(p-q)
print(p*q)
print(p//q)
print(p%q)
print(p**q)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor, Ceil and Rint

In [10]:
import numpy as p2
p2.set_printoptions(sign=' ')
arr1 = p2.array(input().split(),float)
print(p2.floor(arr1))
print(p2.ceil(arr1))
print(p2.rint(arr1))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [7]:
import numpy as np
x,y = map(int,input().split())
p=np.array([input().split() for a in range(x)],int)
print(np.product(np.sum(p,axis=0),axis=0))

2 2
1 2
3 4
24


# Min and Max

In [10]:
import numpy as np
x,y = map(int,input().split())
p=np.array([input().split() for a in range(x)],int)
print(np.max(np.min(p,axis=1),axis=0))

4 2
2 5
3 7
1 3
4 0
3


# Mean, Var, and Std

In [11]:
import numpy as p2
x,y = map(int,input().split())
arr1=p2.array([input().split() for a in range(x)],int)
print(p2.mean(arr1,axis=1))
print(p2.var(arr1,axis=0))
print((p2.std(arr1)).round(11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Dot and Cross

In [20]:
import numpy as np
x= int(input())
p=np.array([input().split() for a in range(x)],int)
q=np.array([input().split() for a in range(x)],int)
print(np.dot(p,q))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer

In [23]:
import numpy as np
p=np.array(input().split(),int)
q=np.array(input().split(),int)
print(np.inner(p,q))
print(np.outer(p,q))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials

In [12]:
import numpy as np2
arr1 = list(map(float, input().split()))
print(np2.polyval(arr1,float(input())))

1.1 2 3
0
3.0


# Linear Algebra


In [13]:
import numpy as pp
n=int(input())
arr1=pp.array([input().split() for _ in range(n)],float)
pp.set_printoptions(legacy='1.13')
print(pp.linalg.det(arr1))

2
1.1 1.1
1.1 1.1
0.0
